### ISSUE TITLE
[Suggestion] Filter mock UI

### ISSUE THREAD

**Issue by Sudharshaun** [Buzzpy/Dev-Encyclopedia#116]
Hey folks, as the page might have to introduce filtering capabilities soon. (Hopefully someone is working on it) I just came up with basic mock designs which you all can review and add suggestions, modify it. This is a very basic mock, we can discuss some of the designs and ideas here if people want to pitch in.
![image](https://github.com/user-attachments/assets/4e893cba-84a6-4040-a589-85691c13bfc2)

**Comment by Buzzpy** [comment]
That's something I had on my mind! It needs some changes, I'll soon share a sample image with you.

**Comment by Buzzpy** [comment]
<img width="1813" alt="image" src="https://github.com/user-attachments/assets/3c8b1f59-6372-4357-bf5f-28363ab3afe2">
Just a mock image, what do you think?

**Comment by RayMathew** [comment]
I was going to work on the filter, and I had a different idea in mind. I'm not sure having that many buttons is a good idea. I'll create a mock sometime today and post here

**Comment by RayMathew** [comment]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/d6144e03-b61c-4a43-af0f-2b8051bd6e60">
Excuse the very rough mockup (how do you guys do mockups btw?), I'll make sure the CSS is in theme with the website when I actually build it.

My idea was one of the two:

- A dropdown select, which shows categories to filter and click on (pictured above). 
- A search - dropdown, where you can also type to search through the categories, since there may come a point where there are too many categories to scroll through.

**Comment by Sudharshaun** [comment]
@RayMathew , I agree with your point placing too many buttons horizontally is not good UI/UX practice. Also the dropdown filter looks good. Only problem for me is it is overlapping the buttons below.

**Comment by RayMathew** [comment]
Not sure how we can overcome the overlapping issue. Is it a problem though? The idea of dropdowns (as I understand) is that we're focusing on something we weren't before, but it isn't important enough to move other things out of the way. 
Even Google's websites overlap stuff when a dropdown is selected.

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/5d210739-7204-469e-8e24-cfdaa307b426">

**Comment by Buzzpy** [comment]
That's great! Having a bunch of buttons is distracting for sure. The drop-down menu sounds good.
