### ISSUE TITLE
Image view on mobile (Android)

### ISSUE THREAD

**Issue by sasakiRoo** [Buzzpy/Dev-Encyclopedia#12]
The site is good! But there's a problem in showing image. The image doesn't show fully.
For example, you searched "Serverless Computing" and click it, there's an image-illustration about what "serverless computing", but doesn't show fully, or being cropped.

**Comment by Buzzpy** [comment]
Thanks for mentioning it!

@pikhosh could this be because of PR #10 or PR #11 ? The images were not responsive at the beginning (it didn't resize accordingly) but this one is new. 

I think it's not scrollable too.

**Comment by RayMathew** [comment]
Do you still want to fix the issue of the full image not being visible?

Suggestions:

1. Make the modal bigger, and use a cross button to exit, rather than tapping somewhere in the background. Not a complete solution but still useful I think, since you don't want to have to scroll so much on an already small screen.
2. Apply CSS so that the image always fits within the width of the screen. Problem with this is that some images can become too small to read.
3. Implement point 2, and also add the feature of zooming in when you tap on the image.

**Comment by Buzzpy** [comment]
Solved with the PR #23 
A huge thank you to @pikhosh !

![image](https://github.com/user-attachments/assets/9237c5d3-d302-483d-a0bc-9126cccd36a7)
