### ISSUE TITLE
Suggestion box / UI for users to recommend new topics

### ISSUE THREAD

**Issue by KC900201** [Buzzpy/Dev-Encyclopedia#95]
Suppose there are certain topics that users are interested in but are not available in the encyclopedia. Is it possible for them to provide feedback on the web to include new issues for the dev site to update them in the future? We can include a suggestion box (UI layout) to inquire the users what would they like to find out for collecting feedback.

**Comment by RayMathew** [comment]
I don't think it's required. Because:

- The Dev Encyclopedia is meant to be used by Devs. They would / should know the basics of going to the Github page and making a suggestion about a missing topic or feature.
- Let's say that there is a very small subset of folks who don't even know how to open the Github page and suggest a topic. Would they really find the website useful? Most of the terms would go over their heads. Yet for them we're going through the cost of building a UI and hosting a DB to store their inputs.

**Comment by bellodamilola** [comment]
@RayMathew Hmmm what about beginners? Or just a random Product Manager that has no major technical understanding of github.

**Comment by RayMathew** [comment]
Agreed, it does make sense for Product Manager type of roles.

**Comment by Anshumanv36** [comment]
Good Idea, if we are implementing it, let me know if you have a design ready, I wanna helpout

**Comment by KC900201** [comment]
@Anshumanv36 thanks. I suddenly have a better idea of this concept. Apologies for the late response due to timezone differences as I'm working on a draft for this. Once it's done, I'll share it here

cc: @RayMathew, @bellodamilola

**Comment by KC900201** [comment]
@RayMathew, @Anshumanv36. I'm sorry for not getting back to you sooner. As mentioned, I drafted a simple UX workflow diagram using draw.io to improve the idea. Instead of creating a new UI box for the user to fill in, what can be improved is automating the process by calling an API to auto-search the information for the new terms and update our existing database (`content/terms`) for the new term. This may kill two birds with one stone by solving the dead links in #92 and auto-updating the existing database. Although it is still in an early stage, I believe we can further improve the workflow by adding the missing steps or considerations that are overlooked.

Else, we can always revert to the new UI layout for users to fill in their required topics

Steps:

1. User types in the search term in the query input
2. System performs searching for info that matches the term 
    2.1. If info exists, system displays info in front end UI (normal workflow)
    2.2 If info doesn't exist, system calls external API to search for relevant information regarding term keyword
       - If API returns successful result, create a new JSON file and fills in the return result from API. Display the new result in UI
       - If API returns empty result or error response, display an empty query result in front end

Considerations for new concept:

- A certain database system needs to be implemented to automate the data fill in process to replace existing json file data. Refer to [astro db](https://docs.astro.build/en/guides/integrations-guide/db/)
- A suitable API needs to be implemented to help the searching mechanism. What I have in mind is certain LLM API (may need license fee)
- (Maybe) Certain keyword filtering mechanism is required to ensure the search query is tech-related 

Share link [here](https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#Wf248b94289629ab0%2FF248B94289629AB0!402059)

![idea_dev_encyclopedia](https://github.com/user-attachments/assets/2a025c49-f58a-44bf-98f6-206ac459d861)

**Comment by Anshumanv36** [comment]
I think it is doable and great idea @KC900201.

- I like where this is headed, but I am also curious how do you plan to tackle the cost bottlenecks mentioned by @RayMathew.

- As far as the JSON to DB files conversion is concerned it had to be done sooner or later also once implemented it would be a much safer and efficient option.

- The quality check is the main concern when automating the creation process as @RayMathew mentioned.

- The security of API can be handled on the backend for robust performance and the possibility of a DDoS attack can be eliminated by simple user timeout logic for POST requests from a particular user(if we do not want the contributors to login first thought then it would be a little different).

**Comment by KC900201** [comment]
@RayMathew and @Anshumanv36, thanks for your feedback. I believe the idea can be broken down into smaller tasks using  divide and conquer approach while brainstorming a workaround for the bottlenecks mentioned. 

1. Converge the existing data storage system using db storage, with [Astro db](https://docs.astro.build/en/guides/astro-db/) as a recommendation
2. Update the existing data fetching APIs to fetch data from db files
3. Draft an improved system design for the new UX workflow of fetching new terms from API, and auto-update the database record with the return results.

Considerations for step 3:

- The sustainability cost for using an LLM API in the long run
- Quality check for user query when typing a new term
- Security of API
- Garbage data maintenance

**Comment by Anshumanv36** [comment]
Nice, I will start working on the database migration part

**Comment by RayMathew** [comment]
Wait, did we actually agree to start working on DB migration?

**Comment by Anshumanv36** [comment]
Looked like that to me, but I might be wrong
Are there still concerns regarding that?

**Comment by RayMathew** [comment]
If there's been some conclusion elsewhere, then I'm not aware. But if it is this thread alone, then we're still just discussing ideas. 
Converting to DB is a massive step, it changes so much of how the website is built, and affects other features too, like filtering. We had also discussed in another thread that converting to DB is not required since the JSON files are pre-rendered into HTML, so there isn't too much load on the frontend. https://github.com/Buzzpy/Dev-Encyclopedia/issues/38.

We have to get a proper consensus, including from the repo maintainer @Buzzpy .

**Comment by RayMathew** [comment]
What we ARE discussing here is if @KC900201 's proposal is worth taking up, and if yes, we first need to research on the 4 bottlenecks mentioned, to make sure our efforts are not wasted before building and pushing the feature to master

**Comment by Anshumanv36** [comment]
Agreed waiting on a consensus

**Comment by RayMathew** [comment]
My take: 
- I'm not convinced any LLM can do a job like what this feature needs, we would need some method of reviewing all created files. But if others are convinced that this is worth trying, I'll contribute towards the research and building too.

**Comment by Sudharshaun** [comment]
> Instead of creating a new UI box for the user to fill in, what can be improved is automating the process by calling an API to auto-search the information for the new terms and update our existing database (`content/terms`) for the new term

The whole idea is good. But very close to being a search engine.

1. We are giving almost all the control to LLM as @RayMathew mentioned. This is a developer maintained repo and as far as I can say let it be a little tedious task for the developer to add a new term as a JSON and raise a PR.
2. We went with AstroJS especially for use cases like this to have static content delivered at front end at ease, if we wanted to have a database serving the content then we could have taken a different route.

These are all great features to implement, but the question is are we going for a overkill? 

Also to solve deadlinks we can have a github action which would take in a Python script to check if the property of JSON file and it's URL is valid.

**Comment by KC900201** [comment]
> We have to get a proper consensus, including from the repo maintainer @Buzzpy .

@Buzzpy, can we have your opinion on this?

**Comment by Buzzpy** [comment]
I'm sorry for not taking part in this conversation, I just waited till you guys were done brainstorming ideas! 🐳

Before giving out my opinions please note that I tried my best to understand what everyone's saying so please correct me if I'm wrong 🙏

Migrating this project to a DB is a questionable approach, given that I decided to go with JSON files for easier and more flexible data management. Security and quality control are also the main issues with letting anyone enter data into a database, as @RayMathew mentioned. Letting APIs create files automatically also raises concerns with regard to the quality of content. Overall, as @Sudharshaun was concerned,  these changes would be an overkill if made too.

That's why adding new terms via PRs is the best approach, IMO.

But I get it, not everyone's going to go through the hustle just to add a new term to the website. For those people, we can just let them fill out a form, which will be immediately reviewed by me or someone else and then added to a JSON file. Since this isn't Wikipedia, I don't think it'll be an exhausting task to review and copy/paste form submissions. Also, when someone searches for a term with no info available, we can show them an option to `"Add <searched-term>"` which redirects them to the submission form.

Also, since the Hacktoberfest is approaching, a lot of new developers will be contributing to this project via GitHub too, hopefully.

**Comment by RayMathew** [comment]
> Also, when someone searches for a term with no info available, we can show them an option to "Add <searched-term>" which redirects them to the submission form.

I like this idea.

**Comment by Anshumanv36** [comment]
PR raised on develop for this fix.

**Comment by KC900201** [comment]
> I'm sorry for not taking part in this conversation, I just waited till you guys were done brainstorming ideas! 🐳
> 
> Before giving out my opinions please note that I tried my best to understand what everyone's saying so please correct me if I'm wrong 🙏
> 
> Migrating this project to a DB is a questionable approach, given that I decided to go with JSON files for easier and more flexible data management (not to mention the cost too). Security and quality control are also the main issues with letting anyone enter data into a database, as @RayMathew mentioned. Letting APIs create files automatically also raises concerns with regard to the quality of content. Overall, as @Sudharshaun was concerned, these changes would be an overkill if made too.
> 
> That's why adding new terms via PRs is the best approach, IMO.
> 
> But I get it, not everyone's going to go through the hustle just to add a new term to the website. For those people, we can just let them fill out a form, which will be immediately reviewed by me or someone else and then added to a JSON file. Since this isn't Wikipedia, I don't think it'll be an exhausting task to review and copy/paste form submissions. Also, when someone searches for a term with no info available, we can show them an option to `"Add <searched-term>"` which redirects them to the submission form.
> 
> Also, since the Hacktoberfest is approaching, a lot of new developers will be contributing to this project via GitHub too, hopefully.

@Buzzpy Duly noted. I understand the concerns on this.

>  when someone searches for a term with no info available, we can show them an option to "Add <searched-term>" which redirects them to the submission form.

I'll work on a modified UX diagram and a basic interface sample for this.

**Comment by KC900201** [comment]
> PR raised on develop for this fix.

@Anshumanv36 May I know the description for this PR? This is to prevent any feature overlapping and redundancy

**Comment by KC900201** [comment]
@Anshumanv36 seems legit. @Buzzpy maybe you can take a look at PR #124. If it's approved, we can close this issue for now. Btw, you may want to have a look at the conflicts and resolve them.

**Comment by Buzzpy** [comment]
Got it, @KC900201 ! I'm a bit busy today, I'll take a look as soon as possible. 
Thanks 🐳

**Comment by KC900201** [comment]
Hi @Buzzpy, as PR #124 is merged, shall I close the ticket with marking it as **resolved**?

**Comment by Buzzpy** [comment]
Yup, for sure!
